### ISSUE TITLE
Need assistance setting up wallet to solo mine Zencash

### ISSUE THREAD

**Issue by Mognar69** [ZencashOfficial/zencash-swing-wallet-ui#10]
Hi,

I'm hoping I can find some help here :) I've googled, searched forums, etc... with no luck. I would like to solo mine and I can't find any information about setting up the wallet to solo mine. With other coins, you would use a --server switch along with a conf file, but there's no info anywhere. 

Would someone be kind enough to tell me what directory the conf file needs to be located in and the contents needed? 

If it's not possible without a solo proxy, just let me know :)

I would greatly appreciate it! 

Mog

**Comment by vaklinov** [comment]
There is a ZENCash miner included with `zend` that is a part of the wallet. However it does only CPU mining, which is inefficient (makes no economic sense). The conf file on Linux is `~/.zen/zen.conf` and you may optionally enable mining in it via the option `gen=1` (but please do not expect any practical/profit results ;-) ).
