### ISSUE TITLE
Zen Swing Wallet not showing Zen cash

### ISSUE THREAD

**Issue by Confused79** [ZencashOfficial/zencash-swing-wallet-ui#103]
Hi, I'm hoping you can help me.  I have a backup wallet.dat file in hopes that I have 
kept my ZenCash secure, however, I don't know how/where to copy it back into the Swing
Wallet software.  Does someone know how this is done?  Thanks!

**Comment by zenportodev** [comment]
The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/

The following document (describing backups) shows how to reach this directory:
https://documentation.zencash.com/display/ZEN/Backup+Full+Chain+Wallet.dat

If the wallet.dat needs to be replaced with a backup, it is a good idea never to overwrite/lose the current verison but to rename it first. The wallet.dat may be copied/restored manually when the GUI wallet/zend are not running!

**Comment by Lincoin25** [comment]
Hello 
I am new to this...
On my iMac I have an error when opening my Zen cash wallet. Please can you assist and guide me?
See below

Thanks
<img width="652" alt="zencash error" src="https://user-images.githubusercontent.com/35370294/41026513-ab6d18b4-696c-11e8-863d-d599bc0e5102.png">

**Comment by Lincoin25** [comment]
I have downloaded the latest zen wallet and replaced the old one and its synchronising

**Comment by St3x** [comment]
Can this resolved issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
