### ISSUE TITLE
sending zenczash

### ISSUE THREAD

**Issue by bobincneo** [ZencashOfficial/zencash-swing-wallet-ui#104]
I sent some zencash to binance and  it said success and there is a transaction # but i have recieved no confirmations and the transaction can not be found on a query to the blockchain. It has been in this state for 24 hrs.

**Comment by zenportodev** [comment]
If the transaction is visible in the GUI wallet but not in the ZEN block explorer, maybe it was not broadcast to the ZEN network due to connectivity problems around the time of sending.

One way to fix this maually may be to use zen-cli. First get the raw/HEX transaction data with:        
`zen-cli getrawtransaction  <TXID>`
This will print a very large HEX sequence like:
```
01000000021c0bbacd18cbd2a947e26f179a214dfc0c22e6bcc8e5e8564a52f0d48e71fc55000000006b4830450
...
95d04b400000000
```
You may then take this sequence and transmit it to the Zen network via the block explorer: https://explorer.zensystem.io/tx/send - paste it in the field Raw transaction data

**Comment by bobincneo** [comment]
Thanks so much it is confirming now on binance.

On June 6, 2018, at 12:19 PM, zenportodev <notifications@github.com> wrote:

If the transaction is visible in the GUI wallet but not in the ZEN block explorer, maybe it was not broadcast to the ZEN network due to connectivity problems around the time of sending.

One way to fix this maually may be to use zen-cli. First get the raw/HEX transaction data with:
zen-cli getrawtransaction <TXID>
This will print a very large HEX sequence like:

01000000021c0bbacd18cbd2a947e26f179a214dfc0c22e6bcc8e5e8564a52f0d48e71fc55000000006b4830450 ... 95d04b400000000 

You may then take this sequence and transmit it to the Zen network via the block explorer: https://explorer.zensystem.io/tx/send - paste it in the field Raw transaction data

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"@context":"<a href="http://schema.org">http://schema.org</a>","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"<a href="https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510">https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510</a>","url":"<a href="https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510">https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510</a>","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"<a href="https://github.com">https://github.com</a>"}} {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ZencashOfficial/zencash-swing-wallet-ui","title":"ZencashOfficial/zencash-swing-wallet-ui","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/ZencashOfficial/zencash-swing-wallet-ui">https://github.com/ZencashOfficial/zencash-swing-wallet-ui</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zenportodev in #104: If the transaction is visible in the GUI wallet but not in the ZEN block explorer, maybe it was not broadcast to the ZEN network due to connectivity problems around the time of sending.\r\n\r\nOne way to fix this maually may be to use zen-cli. First get the raw/HEX transaction data with: \r\n`zen-cli getrawtransaction \u003cTXID\u003e`\r\nThis will print a very large HEX sequence like:\r\n```\r\n01000000021c0bbacd18cbd2a947e26f179a214dfc0c22e6bcc8e5e8564a52f0d48e71fc55000000006b4830450\r\n...\r\n95d04b400000000\r\n```\r\nYou may then take this sequence and transmit it to the Zen network via the block explorer: <a href="https://explorer.zensystem.io/tx/send">https://explorer.zensystem.io/tx/send</a> - paste it in the field Raw transaction data\r\n"}],"action":{"name":"View Issue","url":"<a href="https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510">https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510</a>"}}} { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647", "title": "Re: [ZencashOfficial/zencash-swing-wallet-ui] sending zenczash (#104)", "sections": [ { "text": "", "activityTitle": "**zenportodev**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@zenportodev", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ZencashOfficial/zencash-swing-wallet-ui\",\n\"issueId\": 104,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ZencashOfficial/zencash-swing-wallet-ui\",\n\"issueId\": 104\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510">https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/104#issuecomment-395183510</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 343157870\n}" } ], "themeColor": "26292E" }

**Comment by St3x** [comment]
Can this resolved issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
