### ISSUE TITLE
How to send Zencash from Transparent Wallet

### ISSUE THREAD

**Issue by Sergiomei** [ZencashOfficial/zencash-swing-wallet-ui#105]
How can I send Zencash from my ZENCash wallet? I get the message: "There are no addresses with a positive balance to send cash from!".
The "Transparent balance" shows balance, the 'Private (z) balace is zero.
Should I transfer from "Transparent" to 'Private"? How?
Thank you

**Comment by zenportodev** [comment]
If the ZENCash Desktop GUI Wallet shows transparent balance (in the Overview UI TAB) but the "Send cash" UI TAB shows no addresses with a positive balance to send cash from, maybe the balance (incoming transactions) are not confirmed. What does the "Own addresses" UI TAB show? Is the balance of addresses confirmed there?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one. Sounds like unconfirmed transaction.
