### ISSUE TITLE
error code -1 during wallet recovery (Microsoft)

### ISSUE THREAD

**Issue by ketz3rr** [ZencashOfficial/zencash-swing-wallet-ui#106]
Established ZENCash wallet in October 2017, and stored ZEN coins there. Haven't touched it until now. When opened it - it required update to UI 0.73.1, which I did. The updated version shows 0 coins. Trying to import my private key via "import a single private key" I get the following message:
"An error occurred when importing private key: Error message is: com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Unexpected response from wallet: error code -1 error message: spending key is invalid"
I know the z-key I tried to import is correct - copy & paste. 
Please advise...
Thanks a bunch!

**Comment by zenportodev** [comment]
Version 0.73.1 of the ZENCash Desktop GUI Wallet  is too old. It contains a version of zend that is auto-deprecated. The latest version is 0.80.5

If the Z private key is known to be correct, but there is an error importing it via the GUI, it may be imported via command line:
```
zen-cli z_importkey <Z_PRIVATE_KEY>
```

**Comment by St3x** [comment]
This is how I recovered my wallet on Windows 10 :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by ketz3rr** [comment]
Yes, finally resolved this morning. Thanks a bunch, much appreciated!

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
