### ISSUE TITLE
`ZCashUI` used rather then `ZenCashUI`

### ISSUE THREAD

**Issue by tarrenj** [ZencashOfficial/zencash-swing-wallet-ui#108]
Tested on Apple build.

![screen shot 2018-06-21 at 21 12 20](https://user-images.githubusercontent.com/3710484/41744348-840a8534-7571-11e8-86cd-3f6176ad7a5e.png)

**Comment by josephnicholas** [comment]
@tarrenj ZCashUI is the main class name for the Swing wallet. I will have to refactor the code and rename the ZCash named parameters.

Thanks.

**Comment by tarrenj** [comment]
Do you have a rough estimate of how long that'll take?  It might not be worth it...

**Comment by josephnicholas** [comment]
Fixed on this PR: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/pull/109
