### ISSUE TITLE
Hide zero balance addresses

### ISSUE THREAD

**Issue by il-cyclone** [ZencashOfficial/zencash-swing-wallet-ui#118]
Under the 'Own addresses' tab, it would be nice to have the ability to hide zero balance addresses for better overview like Arizen has.

**Comment by St3x** [comment]
Is this issue still relevant ?

This is how I __deleted__ the zero-balance/non-used addresses from my wallet on Windows 10 :
- Use the Wallet -> Export private keys... menu to export your private keys
- Open the exported file, delete the __zero-balance__ addresses you don't want to keep (the whole lines) and save the file
- Close the Swing Wallet
- Delete your `%APPDATA%\zen\wallet.dat`
- Open the Swing Wallet
- Use the Wallet -> Import private keys... menu to import your private keys

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
