### ISSUE TITLE
Zencash Swing Wallet 0.74.7 - General Unexpected Critical error (code -1)

### ISSUE THREAD

**Issue by rsqu4red** [ZencashOfficial/zencash-swing-wallet-ui#127]
Hello all,
I ran my wallet after a few month and i am getting this message:

![grafik](https://user-images.githubusercontent.com/24811312/44947639-61e66900-ae10-11e8-86cf-7ca549dc6b8a.png)

I think I have Version 0.74.7 of the zencash swing wallet.
I am runnung on linux ubuntu 16.04.
Reading all the Issues I think I have to reindex. But before I want to backup my wallet.dat.
But i cant find the wallet.dat and i cant open the wallet to create one. How can I backup my wallet?

Could somebody help me?
Thanks a lot!

**Comment by St3x** [comment]
This is how I recovered my wallet on Windows 10 (translate to Ubuntu) :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
