### ISSUE TITLE
When attempting to move ZenCashWallet to Applications folder on Mac: "The operation can’t be completed because you don’t have permission to access some of the items."

### ISSUE THREAD

**Issue by missilelaunchr** [ZencashOfficial/zencash-swing-wallet-ui#130]
I was running a previous version of ZenCashWallet on Mac (High Sierra) and attempted to upgrade to the latest version.  When I attempted to drag the ZenCashWallet into the applications folder the first time, I was prompted for admin creds on my mac which I supplied, it began copying files and then I received the error: "The operation can’t be completed because you don’t have permission to access some of the items."

I previously have 0.81.x installed

I also observed that the ZenCashWallet is now missing from the applications folder.  I attempted several more times but immediately receive the same error: "The operation can’t be completed because you don’t have permission to access some of the items.".

I changed my user account to an administrator, and tried the process again however it still fails with this error. Unfortunately the wallet is inaccessible and I can't seem to re-install the wallet either.  I may try and re-install my previous version if I can determine exactly what it was, it was 0.81.x but I don't know what version number was in the x position.

It's also worth noting, that the last time I was running the wallet prior to attempting to upgrade it was syncing the blockchain and showed the following error several times, this error is also in the logs:
"[Thread-126] [Sat Sep 08 16:30:43 PDT 2018] [ERROR] Unexpected error:  
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)"

The zend debug logs also have the following error:
"2018-09-08 23:28:06 Error: This version has been deprecated as of block height 332576. You should upgrade to the latest version of Zcash. To disable deprecation for this version, set -disabledeprecation=2.0.11."

**Comment by missilelaunchr** [comment]
I did some additional testing, if I simply try and copy the ZenCashWallet file from the .DMG to any folder on my mac I get the error "The operation can’t be completed because you don’t have permission to access some of the items."  It seems as though the mac permissions or "Mac UAC" is not being quiesced successfully.

**Comment by missilelaunchr** [comment]
Please re-publish the mac version of the wallet, I think the file permissions built into the files in the .DMG are bad or some other issue.  Can't even copy the file out of the .DMG without getting the permission error.

**Comment by missilelaunchr** [comment]
I tried installing the mac swing wallet 0.83.1 using the released .DMG on a completely different mac (High Sierra) that has never had the wallet installed and received the following error when attempting to copy the ZenCashWallet to the applications folder as is required on a mac: "The operation can't be completed because you don't have permission to access some of the items."

I appreciate everyones effort on this project, however 0.83.1 is truly a bad release and bad build, unequivocally.

**Comment by missilelaunchr** [comment]
This problem continues with 0.84.1 for mac...

**Comment by missilelaunchr** [comment]
This problem continues with 0.85.1 for mac.  Please I beg, test installing the mac release on a fresh mac before considering it a shippable release.  This issue isn't 'my computer' as I've tried on different mac's and reproduced this on all.  Perhaps for some reason the developers Mac does not experience this problem because the product has been installed in different ways during dev/test.

**Comment by Sto1cNate** [comment]
@zennermac @cronicc any information about this particular issue?

**Comment by zennermac** [comment]
@Sto1cNate I have personally tested this on Mojave, High Sierra and Sierra.
When we perform our tests we use the same installer as is published to the release.
The only time I have seen an issue like this is when a security/AV product sees some of the files as a threat and either places them in quarantine or removes them completely.

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
