### ISSUE TITLE
Wallet.dat is corrupted but readable with STRINGS/HexDump

### ISSUE THREAD

**Issue by mex20** [ZencashOfficial/zencash-swing-wallet-ui#135]
A while ago the swing wallet corrupted the wallet.dat file while doing the error 1 nonsense. I am able to read most of the wallet.dat with HexDump and Strings. Where can I find the private key(s) in the wallet.dat file? I can find the string for each address, but I don't know where the private keys are stored in the wallet.dat file. 

I tried to contact support, but they were not helpful because they just suggested that I use a backup. After I told them it was not possible to use a backup, and asked them about the structure of the wallet.dat file, they stopped responding to me.

I read that on the Zcash repository, Radix42 said that they were making a script to repair damaged wallets/extract private keys. Is there such a script for ZenCash? My attempts with BereklyDB tools were moot, but I also am not an expert with them.

**Comment by psyraxaus** [comment]
I dont know the structure of the wallet.dat BerkleyDB, but it is possible to download the myzenwallet.io code from https://github.com/ZencashOfficial/myzenwallet and load the wallet.dat into that to gain access to the private keys.

Once you load the page, you click on the gear icon and select load wallet.dat, then once the wallet.dat loads you will see the t-addresses.  To export the private keys, click on the export tab and then download private keys button.

This only reveals the public t-addresses not the private z-addresses

**Comment by mex20** [comment]
That seems to be able to browse and deal with corrupted database wallet.dat files! Thanks a lot @psyraxaus
