### ISSUE TITLE
sapling? update

### ISSUE THREAD

**Issue by equ1miner** [ZencashOfficial/zencash-swing-wallet-ui#138]
do these functions exist for groth16

using your latest downlod.

zen-cli z_getnewaddress sapling
error code: -1
error message:
z_getnewaddress

Returns a new zaddr for receiving payments.

Arguments:

Result:
"horizenaddress"    (string) The new zaddr

Examples:
> zen-cli z_getnewaddress
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_getnewaddress", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/

**Comment by Sto1cNate** [comment]
Sapling addresses are not enabled yet. Should be enabled in next upgrade cycle.

**Comment by cronicc** [comment]
Pending Sapling implementation on main chain.
