### ISSUE TITLE
Norton 360 keeps removing zen-cli.exe  and zend.exe 

### ISSUE THREAD

**Issue by BitcoinNovice** [ZencashOfficial/zencash-swing-wallet-ui#14]
I can not get my widows wallet set up because norton 360 keeps removing zen-cli.exe  and zend.exe 

I have excluded these from norton scans and turned of the ws.repputation portion of the scan yet still problem persists.  Called norton need to escalate. Any ideas?

**Comment by vaklinov** [comment]
As a start it would be good to double check the integrity of the binaries you have. Assuming you downloaded this release 
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/Release_0.73.1.md
of the ZENCash Desktop GUI Wallet for Windows, you can compare the `zen-cli.exe` and `zend.exe` with the respective files originally released by the ZEN-core project:
https://github.com/ZencashOfficial/zen/releases/tag/v2.0.9-4
https://github.com/ZencashOfficial/zen/releases/download/v2.0.9-4/Zen_Win_binaries_v2.0.9-4-2045d34.zip
If the files are the same, then this is an issue of the AV scanner (false positive result)...

**Comment by BitcoinNovice** [comment]
I know this must sound really dumb but I was able to check the hash using QuickHash V2.8.4 but when I tried to compare the each of two files zen-cli.exe and zend.exe.  I could not get quick hash to select them.

**Comment by BitcoinNovice** [comment]
I think I finally figured it out. What a massive waste of time.  ZEN-clli.exe, zend.exe and zen-tx.exe all have to be in the same folder as the app ZenCash SwingWalletUI.exe

**Comment by vaklinov** [comment]
`zen-cli.exe` and `zend.exe` need to be in the same directory as `ZENCashSwingWalletUI.jar`

**Comment by zenportodev** [comment]
Support case - presumed to be solved.
