### ISSUE TITLE
ZenCash Swing Wallet Issue

### ISSUE THREAD

**Issue by sameermatta** [ZencashOfficial/zencash-swing-wallet-ui#141]
Hi,

When I load the new 0.86 wallet, I keep getting this error:
[https://imgur.com/DB5ktOL](https://imgur.com/DB5ktOL)

Please assist in how to get the wallet to successfully load. 

Thanks!

**Comment by Sto1cNate** [comment]
What files are in `%appdata%\ZcashParams\` ?

**Comment by Sto1cNate** [comment]
This appears to be already be in progress on another medium (reddit) through one of the Horizen support members, Psyrax. 

https://www.reddit.com/r/Horizen/comments/bl5ck8/zencash_swing_wallet_problem/

**Comment by zennermac** [comment]
Closing as support is being given via reddit
