### ISSUE TITLE
How horizen swing-wallet migrates block directory files

### ISSUE THREAD

**Issue by zhjgit** [ZencashOfficial/zencash-swing-wallet-ui#143]
The Windows 7 system I use has been running horizen security nodes for more than a year, but now when I synchronize swing wallets, all my block data is stored in C:\Users\Administrator\AppData\Roaming\Zen. As a result, the space of my C disk has been reduced and can't be supported. Is there any way to migrate the directory of horizen blocks?

**Comment by Sto1cNate** [comment]
@zhjgit 

You should be able to modify that location to another hard drive by specifying the folder location using the datadir flag in the zen.conf.

Add the following to your zen.conf and update the folder location where you store the blocks, chainstate, wallet.dat

`datadir="folder/location/here"`

You should need to cut and paste the blocks and chainstate folders into the new directory as well as the wallet.dat file first before re-launching the wallet.

**Comment by zhjgit** [comment]
![aa1](https://user-images.githubusercontent.com/11417141/59563075-affaef00-9067-11e9-97b4-cf2fdcd756d5.png)
Is that right? First I copy C：\ Users \ Administrator \ AppData \ Roaming \ Zen to disk F, then add datadir= F: \Zen to zen. conf, just like in my picture?

**Comment by Sto1cNate** [comment]
@zhjgit 

I believe you need to put the location in quotes after the equal (=) sign. But yes, otherwise should be correct.

**Comment by zhjgit** [comment]
@Sto1cNate 
Okay, thank you. I'll try it first.
Should be filled in like this? datadir="F:\Zen"

**Comment by Sto1cNate** [comment]
@zhjgit 
I believe this is correct. Just be sure you have first copied over the blocks, chainstate folders from the original directory first and made sure that zend.exe was not running before trying to copy over the wallet.dat to that new location.

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.

**Comment by FosLoDa** [comment]
I added below to %APPDATA%/Zen/zen.conf file.

datadir="D:/Zen"

Then, I copied %APPDATA%/Zen to D:/Zen
But, below error message is appeared when run exe.

> A general unexpected critical error has occureed:
> error: couldn't connect to server: EOF reached (code 1)
> (make sure server is running and you are connecting to the correct RPC port)
> See the console/logfile output for more detailed error infonmation!

How to slove this issue?
