### ISSUE TITLE
Error dialog displayed after sitting idle for hours does not close

### ISSUE THREAD

**Issue by ADumaine** [ZencashOfficial/zencash-swing-wallet-ui#148]
A dialog box with a message but no action buttons to close or acknowledge popped up after sitting idle overnight.  The dialog would not close. Swing became unresponsive. Had to end the task to get swing to close.   Swing usually becomes unresponsive after a 6-8 hours on this computer, but I have never seen this dialog before.

![image](https://user-images.githubusercontent.com/1069218/62315553-69602900-b44a-11e9-8833-b6c33278c9ae.png)

**Comment by zennermac** [comment]
Could you provide any relevant log files so we can get a better insight as to what is going on.

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
