### ISSUE TITLE
Connection timeout during proving-key downloading

### ISSUE THREAD

**Issue by axifive** [ZencashOfficial/zencash-swing-wallet-ui#15]
Hello. When I first run the wallet it started downloading proving key, but after a few minutes, I saw a dialog with timeout error. 
I try it three times and then downloaded this file with `wget`, it supports continuation of the download. I think that it is necessary to add the continuation of the download after the connection timeout.

![2017-10-22 0 27 39](https://user-images.githubusercontent.com/844963/31856311-7aa5e8e0-b6c6-11e7-9e54-dd7e0ec0fdfe.png)

![2017-10-22 1 17 04](https://user-images.githubusercontent.com/844963/31856332-d32a9e70-b6c6-11e7-82cb-03b3c0ff97fa.png)

**Comment by vaklinov** [comment]
Accepted as an enhancement to be implemented - resumption of proving key download.

**Comment by zennermac** [comment]
This is technically more of an infrastructure challenge than a wallet problem and not directly related to zencash-swing-wallet-ui. 
I would anticipate that now Sphere By Horizen is available, this functionality will likely not be built into Swing going forward.

I would suggest adding this a feature request in the Sphere By Horizen Repo
https://github.com/ZencashOfficial/Sphere_by_Horizen
