### ISSUE TITLE
Application name in Windows task manager shows description instead of app name

### ISSUE THREAD

**Issue by todw1fd** [ZencashOfficial/zencash-swing-wallet-ui#151]
When running Swing wallet, Windows task manager displays a description of the application instead of the application name in the app name column.  
![swing_task_mgr_issue](https://user-images.githubusercontent.com/35246503/68432467-16e58580-017a-11ea-9d5d-4d5f9cc8da62.jpg)

**Comment by cronicc** [comment]
Thanks for reporting this, will be fixed in next planned release.
