### ISSUE TITLE
Internet Is Fine & I've Had The Swing Wallet Open & Still 0 Connections

### ISSUE THREAD

**Issue by ChurchOfNotNothing** [ZencashOfficial/zencash-swing-wallet-ui#152]
I'm using the GUI Swing Wallet on Mac OS X Mojave 10.14.3 (18D109). The wallet was open for a while and had connections and was syncing properly. Now, I have 0 connections and this is after reopening the program. I'm definitely using Wallet 0.88.0 and I really don't know how to get the connections going again?

**Comment by uanl979** [comment]
hey @ChurchOfNotNothing 

Do you still have this issue?
Are you running the latest Swing version?

Regards

**Comment by uanl979** [comment]
I will be closing this issue, since I had no response, for any future issues (if still present) please raise a ticket at our support system at support.horizen.global We'll gladly provide you support :)
