### ISSUE TITLE
Price Values missing

### ISSUE THREAD

**Issue by ADumaine** [ZencashOfficial/zencash-swing-wallet-ui#155]
![image](https://user-images.githubusercontent.com/1069218/76649564-33297280-651e-11ea-8454-9a31c28d2533.png)

**Comment by uanl979** [comment]
hey @ADumaine 

We are aware of this issue and we have this on our backlog as an item to fix. @cronicc 

We'll keep you posted in the near future once this issue is solved :)

Regards

**Comment by uanl979** [comment]
Closing this issue, I'll keep you posted when the price api is fixed.
