### ISSUE TITLE
Why are the instructions for backup only shown once 

### ISSUE THREAD

**Issue by BitcoinNovice** [ZencashOfficial/zencash-swing-wallet-ui#16]
The instructions for backup and where to store them are only shown once and its not possible to copy and paste.  This is a problem and a bad idea.  How do I see them again with out uninstalling and reinstalling.

At least if I could copy them. Now I dont know how to do it.  Very user unfriendly for people who are not developers.

**Comment by ToLive** [comment]
![xnviewmp_2017-10-22_22-21-51](https://user-images.githubusercontent.com/2019736/31863409-92339be0-b777-11e7-9655-b2448cbdb15c.png)

**Comment by vaklinov** [comment]
Accepted as an enhancement to be implemented - the UI information dialogs of this type are to be shown until the user decides to click "Do not show this again"... a new button to be added.

**Comment by vaklinov** [comment]
The issue is fixed in the Git master branch. There is a button of type "Do not show this again" ...
