### ISSUE TITLE
testnet error message

### ISSUE THREAD

**Issue by GroovyGrovesy** [ZencashOfficial/zencash-swing-wallet-ui#17]
I've just set up a MN on a VPS and am getting my local wallet ready to receive the testnet coins for testing.  I set testnet=1 in the conf and when the wallet loads I get this.

![image](https://user-images.githubusercontent.com/7847340/31889964-76f7b258-b7f9-11e7-87d7-40970479b7a9.png)

Anything I can do about this?

**Comment by vaklinov** [comment]
Newer versions of the wallet explain the problem to the user more clearly (in the terms I described), but still it is up to the user to take action to fix it.

**Comment by GroovyGrovesy** [comment]
Thanks Vaklinov, I found that same answer on the slack channel.
