### ISSUE TITLE
regarding the Swing Wallet: Seeds and Encryption & Backup/Recovery

### ISSUE THREAD

**Issue by BitcoinNovice** [ZencashOfficial/zencash-swing-wallet-ui#18]
1I     dont understand the security for the Wallet. I use a Trezor for my Bitcoin. And other wallets.
        Is there any kind of encryption? Are there Seeds?

        What methodology is used?  Its not apparent to me. Am I missing it, if not its wholly inadequate.

2.      If my computer Crashes how do I recover my pvt keys.  I can not figure that out either.
          Am I missing something.  Or is a company which is concerned with privacy completely 
          unconcerned with Security, its seems antithetical to me.  Makes me consider selling my newly 
          acquired coins.

**Comment by vaklinov** [comment]
The ZENCash Desktop GUI Wallet is technically a UI wrapper over the ZENCash command line tools. The ZEN private keys are stored in the `wallet.dat` file and it does not yet support encryption at file level. For that matter ZCash does not support encryption yet either... Encryption will surely be supported in the future.

One ZEN wallet that already supports encryption is Arizen:
https://github.com/ZencashOfficial/arizen

**Comment by St3x** [comment]
Swing Wallet doesn't support encryption.

This is how I recovered my wallet on Windows 10 (if your computer crashes) :
- Have a backup of your private keys (Wallet -> Export private keys...) or your `%APPDATA%\zen\wallet.dat` file (if you can't open the Swing Wallet for some reason)
- Uninstall/Delete the existing Swing Wallet and the `%APPDATA%\zen` directory
- Download, extract and run the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases)
    - Don't replace anything, let it start the synchronization with a brand new and empty wallet
- With the private keys simply use the Wallet -> Import private keys... menu and import your private keys
- With the `%APPDATA%\zen\wallet.dat` file there can be version-related issues so you have to extract your private keys from the file :
    - Go to https://myzenwallet.io/
	- Settings (cog) -> Load wallet.dat -> Close (cross)
	- Select wallet.dat file
	- Export -> Download Private Keys
	- Now in the Swing Wallet use the Wallet -> Import private keys... menu and import your private keys
- You will see all your funds when the Swing Wallet will be fully synchronized

Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
