### ISSUE TITLE
Account not credited with the funds sent to my wallet

### ISSUE THREAD

**Issue by CYCLONE1425** [ZencashOfficial/zencash-swing-wallet-ui#22]
After setting up my wallet I sent small amounts of ZEN from BITTREX to my wallet address and it was never credited to my wallet even though BITTREX shows them as completed. I updated to the latest version of the wallet and still nothing.

**Comment by CYCLONE1425** [comment]
Thanks for responding so quickly.

I have to admit that I never waited until it showed 100% sync as I gave up after about 2 hours. I will try again and see if it completes.

**Comment by YvetteO** [comment]
How long does the synch process take? I've been waiting to receive my funds since 3p.m. (4.5 hours), and still no show. How can I find the blockchain that it was sent on?

**Comment by YvetteO** [comment]
How long does the syncing process take? I've been waiting to receive my funds since 3p.m. (4.5 hours), and still no show. How can I find the blockchain that it was sent on?

**Comment by YvetteO** [comment]
I created a transaction id# 39588fa28b26dbec8748f06732276958e194dc9b98b8acf677c1099b03886b8f in the amount of  6.97520420 ZEN from Cryptopia exchange to my ZenCash Swing Wallet UI public address: zndD4qo5wRNZX3b1jce81noJpAW119HVZER at 2.59pm, and I still haven't receiveed my deposit. Unable to find either the transaction or the address on the blockchain explorer.

**Comment by vaklinov** [comment]
@CYCLONE1425 Please confirm that it works as expected after ZEN blockchain is 100% synchronized.

**Comment by CYCLONE1425** [comment]
Yes it did work, took over a day to synchronize but it did work, thanks.

C.

**Comment by zenportodev** [comment]
Support case - solved.
