### ISSUE TITLE
Deposit not received in my ZenCash Swing Wallet 

### ISSUE THREAD

**Issue by YvetteO** [ZencashOfficial/zencash-swing-wallet-ui#24]
I created a transaction id# 39588fa28b26dbec8748f06732276958e194dc9b98b8acf677c1099b03886b8f in the amount of 6.97520420 ZEN from Cryptopia exchange to my ZenCash Swing Wallet UI public address: zndD4qo5wRNZX3b1jce81noJpAW119HVZER at 2.59pm, and I still haven't receiveed my deposit. Unable to find either the transaction or the address on the blockchain explorer.

How long does the syncing process take? I've been waiting to receive my funds since 3p.m. (4.5 hours), and still no show. How can I find the blockchain that it was sent on?

**Comment by vaklinov** [comment]
Hi @YvetteO ,
   The transaction is on the blockchain:
https://explorer.zensystem.io/tx/39588fa28b26dbec8748f06732276958e194dc9b98b8acf677c1099b03886b8f
If your ZEN wallet is synchronized 100% I expect it to show the transaction... Is the blockchain 100% synchronized?

Best regards,
   Ivan

**Comment by vaklinov** [comment]
@zenbob1 Unless the blockchain is 100% synchronized, the wallet will not show the latest transactions made. The wallet only sees the transactions before the latest blockchain synchronization date. Please wait for 100% sync.

**Comment by zenbob1** [comment]
Sorted! thanks

**Comment by YvetteO** [comment]
Thank you for your prompt response, Ivan. 
The wallet was not at 100% sync, and had to catch up from a date of December 2016 to the current date. It is now synced, and thank you for the Zen Explorer url. Comes in handy.

**Comment by princethesinger** [comment]
Hello is is taking ages to synch my swing wallet like  2 days to do 5%..is there a way to download the block chain as a zip file and load into wallet files please thanks

**Comment by vaklinov** [comment]
Synchronization of only 5% in 2 days is terribly slow indeed. Normally it takes on the order of 6-12 hours for full 100% sync. on a PC with relatively good CPU/HDD/network connection.

Unfortunately I am not aware of anyone offering a direct block-chan download.

If your internet connection is slow, you may first try the Arizen wallet: it does not need the full blockchain locally so it needs a lot less traffic: https://github.com/ZencashOfficial/arizen

**Comment by princethesinger** [comment]
Thanks Ive purchased a new computer hope it will help


________________________________

**Comment by zenportodev** [comment]
Support case - presumed to be solved.
