### ISSUE TITLE
Installing on second PC

### ISSUE THREAD

**Issue by Canefire** [ZencashOfficial/zencash-swing-wallet-ui#25]
When I install Swing Wallet on another PC I am given a different address. How to I transfer the settings from my first PC installation to my new one? Or is there some way to log into that wallet from the new wallet?

**Comment by vaklinov** [comment]
The `wallet.dat` file contains the private keys to controlling the ZEN coins. The `wallet.dat` file may be copied manually when the GUI wallet and `zend` are not running. Make sure you have a backup copy of it on a safe external medium.

The `wallet.dat` file may also be transferred from one PC to another ... when the GUI wallet and `zend` are not running!

**Comment by Canefire** [comment]
Thank you for the info. I cannot find the wallet.dat file. This is a windows installation, and I have searched everywhere in the wallet folder where I unzipped the download. Can you suggest a proper path to the file?

 

Frank Wyatt

Ma.k-Tau-IG

     maksig

**Comment by Canefire** [comment]
Found wallet.dat in users..appdata...roaming. Exchanged into new PC, worked as it should. Thanks for the help.
