### ISSUE TITLE
Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by ShashokKV** [ZencashOfficial/zencash-swing-wallet-ui#26]
Hello, I get this error immediately after clicking OK in the first messagebox (about downloading 900Mb e.t.c.). Here is log file:
[ZENCashGUIWallet_2017_11_debug.log](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/files/1452000/ZENCashGUIWallet_2017_11_debug.log)

**Comment by vaklinov** [comment]
This SSL connection failure is very strange:
```
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
```
I could not reproduce it. During this operation, the GUI wallet downloads the key `https://zensystem.io/downloads/sprout-proving.key` and places it in directory `%APPDATA%\ZcashParams`.

Please try to do this download manually using a browser... to see if it will be successful then.

**Comment by Chess100500** [comment]
When I try to click on the link that you provided it redirects me to https://f001.backblazeb2.com/file/TrustedSetup/sprout-proving.key, which doesn't open too (I get ERR_SSL_PROTOCOL_ERROR).  If I try to change https to http, then this link is blocked by my provider firewall, which says that this site contains  Mal/DownLnk-D virus.
But still I was able to download proving key from zensystem.io using proxy. After placing it into AppData\Roming\ZcashParams the wallet successfully opened. Thank you!

**Comment by zenportodev** [comment]
Support case - presumed to be solved.
