### ISSUE TITLE
Transfer account to second PC

### ISSUE THREAD

**Issue by Canefire** [ZencashOfficial/zencash-swing-wallet-ui#27]
Migrating wallet.dat from PC1 to PC2 did change the address under Own Addresses to the same as the original, however balance and transaction data are not showing on the second PC. My concern now is that mining payments may be sent to the first PC, which I am shutting down. How do I get everything on the new PC, and close out the original?

**Comment by vaklinov** [comment]
If the blockchain is synchronized 100% (lower right panel of the GUI Wallet Overview TAB) on both PC1 and PC2, they should both show the same ZEN balance... Payments are not sent to PC1 or PC2; they are sent to a ZEN address, and what matters is whether you have control of the wallet with this address...

The most important thing is to keep a backup of your `wallet.dat` file. The `wallet.dat` file needs to be backed up periodically e.g. for every 50 outgoing T-> transactions, also also when new Z addresses are created in it...

**Comment by Canefire** [comment]
The wallet did update transaction after some time. All seems to be working fine now.
