### ISSUE TITLE
Unhandled exception on wallet startup

### ISSUE THREAD

**Issue by bitstr3am** [ZencashOfficial/zencash-swing-wallet-ui#28]
Full disclosure, I was running the wallet on a Win10 VM. It was still performing init sync. I powered off the VM to adjust memory (increase) and added 2 procs.  Restarted and ran the wallet. The issuer repro's 100%. I was able to work around by 'zend -reindex'. Should we make this more robust, can we reliably auto apply -reindex or checkpoint the index etc?

See error dialog below.
![startupfailure](https://user-images.githubusercontent.com/3313260/32538974-d397dd2e-c41c-11e7-9a2a-8c528c947cb9.jpg)

Logs:

[Thread-14] [Wed Nov 08 00:30:52 PST 2017] [INFO] Gathering of dashboard daemon status data done in 78ms. 
[AWT-EventQueue-0] [Wed Nov 08 00:30:52 PST 2017] [INFO] Exiting ... 
[Thread-9] [Wed Nov 08 00:30:52 PST 2017] [INFO] Stopping zend because we started it - now it is alive: true 
[Thread-9] [Wed Nov 08 00:30:52 PST 2017] [INFO] Stop command issued: Zen server stopping
 
                                                                               [main] [Wed Nov 08 00:31:53 PST 2017] [INFO] Starting ZENCash Swing Wallet ... 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] OS: Windows 10 = WINDOWS 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] Current directory: C:\zen\app 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] Class path: C:\zen\app\ZENCashSwingWalletUI.jar;bitcoinj-core-0.14.5.jar 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] Environment PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Billy\AppData\Local\Microsoft\WindowsApps; 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] Using ZENCash utilities: zend: C:\zen\app\zend.exe, zen-cli: C:\zen\app\zen-cli.exe 
[main] [Wed Nov 08 00:31:53 PST 2017] [INFO] zend is not runing at the moment or has not started/synchronized 100% - showing splash... 
[main] [Wed Nov 08 00:31:54 PST 2017] [INFO] Splash: checking if zend is already running... 
[main] [Wed Nov 08 00:31:56 PST 2017] [INFO] Splash: zend will be started... 
[main] [Wed Nov 08 00:32:12 PST 2017] [ERROR] Unexpected error:  
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:564)

**Comment by vaklinov** [comment]
The problem of blockchain corruption/inconsistent state is one that occurs often in cases of power outage etc. I do not think it is  good idea for the GUI wallet to do `zend -reindex` automatically every time `zend` somehow refuses to run ... there may be many other reasons for the problem.

I think you need to take the issue of blockchain corruption/inconsistent state to the ZEN-core developers...

**Comment by bitstr3am** [comment]
Thanks, will open on ZEN-core.

**Comment by zenportodev** [comment]
ZEN-Core issue.
