### ISSUE TITLE
Add Name Column to Own Addresses

### ISSUE THREAD

**Issue by bitstr3am** [ZencashOfficial/zencash-swing-wallet-ui#29]
After creating a few addresses it can be hard to track which is for what purpose. 

Having a user editable column e.g. 'Name' would allow the user to have a human readable nickname to keep track and minimize the chance of accidentally using the wrong address for a receive or worse a send.

@vaklinov Are Git Issue Labels user editable? I was going to tag as enhancement.

**Comment by vaklinov** [comment]
The existing "Address book" functionality mostly fulfils this requirement: Having a user editable column e.g. 'Name'.

As an enhancement the wallet could be made more convenient - to be like Bitcoin-QT.

Git labels are editable... but edits rights are required.

**Comment by bitstr3am** [comment]
Thank you vaklinov, I think you understood the ask but let me clarify in case.

Address book is good to having a human readable description for target addresses.

My ask is to have the same for wallet addresses (source) on the Own Address tab. Having a number of addresses it would be much simpler to keep them straight.

**Comment by zenportodev** [comment]
This is now implemented.
