### ISSUE TITLE
Unable to delete addresses

### ISSUE THREAD

**Issue by Webisoft** [ZencashOfficial/zencash-swing-wallet-ui#30]
Is this function missing or am I just blind? Let me know pls.

**Comment by vaklinov** [comment]
Addresses are not meant to be deleted from the wallet. The ZEN core node software has no such feature.

**Comment by Webisoft** [comment]
I see, is there any way to delete em?

**Comment by vaklinov** [comment]
If deleting addresses is so important the only practical way to do it, I can think of, is to move to a new/fresh wallet (new `wallet.dat`).

**Comment by solid90** [comment]
I've created 3 addresses on accident by just exploring around the wallet. How annoying to not be able to delete the unwanted addresses. This should be something that is incorporated into the wallet in future builds to help improve the user experience.

**Comment by vaklinov** [comment]
Accepted as an enhancement request. However this can only be done by the GUI wallet is there is support for it in the ZEN-core software... some day.

**Comment by TeeVee17** [comment]
I did the same and was trying to figure out how to delete the extras. now I know it can't be done.

**Comment by jeffrichley** [comment]
Need to +1 this.  Very annoying to have dead addresses lying around.  Killin my OCD.

**Comment by St3x** [comment]
This is how I __deleted__ the zero-balance/non-used addresses from my wallet on Windows 10 :
- Use the Wallet -> Export private keys... menu to export your private keys
- Open the exported file, delete the __zero-balance__ addresses you don't want to keep (the whole lines) and save the file
- Close the Swing Wallet
- Delete your `%APPDATA%\zen\wallet.dat`
- Open the Swing Wallet
- Use the Wallet -> Import private keys... menu to import your private keys

Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
