### ISSUE TITLE
Init sync performance improvement

### ISSUE THREAD

**Issue by bitstr3am** [ZencashOfficial/zencash-swing-wallet-ui#32]
Full sync is way too slow; given current bug that require re-sync it's not only inconvenient but impedes testing progress for folks so may deserve priority elevation beyond what performance issues might normally receive. 

Opening issue to track. If this is already tracked please close with reference. If cause is ZEN-core please indicate and I can open on that repo.

**Comment by vaklinov** [comment]
The blockchain synchronization is handled by `zend` - not by the GUI. I think this issue needs to be taken to the ZEN Core project.

**Comment by St3x** [comment]
Can this issue be closed as it's not a Swing Wallet one ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
