### ISSUE TITLE
Wallet process/DB not resilient to sudden process termination

### ISSUE THREAD

**Issue by bitstr3am** [ZencashOfficial/zencash-swing-wallet-ui#33]
I've got an occasional bugcheck on a Windows box due to a buggy NVidia driver.

What I've noticed is when this happens I often see the attached Wallet splash status, presumably due to DB check or sync.  It lasts a very long time. Not sure what logs to examine?

Given the ever growing cost of sync can we harden the for this case e.g. power outage to handle (i.e. DB transaction semantics)? 

![activationbestchain](https://user-images.githubusercontent.com/3313260/32651976-a425217c-c5b7-11e7-9b4b-e9d921cabfd2.jpg)

**Comment by vaklinov** [comment]
The blockchain synchronization and the "activation of best chain" is handled by zend - not by the GUI. I think this issue needs to be taken to the ZEN Core project.

**Comment by St3x** [comment]
Can this issue be closed as it's not a Swing Wallet one ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
