### ISSUE TITLE
Are you planing to solve encryption problem for wallet ?

### ISSUE THREAD

**Issue by pukis3891** [ZencashOfficial/zencash-swing-wallet-ui#36]
Are you planing to solve encryption problem for wallet ?

**Comment by vaklinov** [comment]
The ZEN private keys are stored in the `wallet.dat` file by the ZEN core node and it does not yet support encryption at file level. For that matter ZCash does not support encryption yet either... Encryption will surely be supported in the future.

One ZEN wallet that already supports encryption is Arizen:
https://github.com/ZencashOfficial/arizen

**Comment by St3x** [comment]
Swing Wallet doesn't support encryption.
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
