### ISSUE TITLE
trouble downloading to windows

### ISSUE THREAD

**Issue by bethscapade** [ZencashOfficial/zencash-swing-wallet-ui#38]
I am not able to download the zencash swing wallet to my laptop on windows.
First Norton disables it and when I correct that, the windows says the file cannot be found
Please help

**Comment by vaklinov** [comment]
This seems to be the same problem as reported in https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/14

**Comment by vaklinov** [comment]
zen-cli.exe and zend.exe need to be in the same directory as ZENCashSwingWalletUI.jar

**Comment by vaklinov** [comment]
@bethscapade Is your PC running 64-bit Windows? having at least 8 GB RAM?

**Comment by zenportodev** [comment]
Support case - no further information received.
