### ISSUE TITLE
The repository does not have a release file for Mint.

### ISSUE THREAD

**Issue by jebbgrenham** [ZencashOfficial/zencash-swing-wallet-ui#39]
> W: The repository 'https://zencashofficial.github.io/repo serena Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> E: Failed to fetch https://zencashofficial.github.io/repo/dists/serena/main/binary-amd64/Packages  404  Not Found
>

**Comment by jebbgrenham** [comment]
Change your mint sources zencash release to xenial if you do want to use the wallet for now, until the repository is fixed.

**Comment by vaklinov** [comment]
I think the right place to report this issue is the ZEN APT repository project:
https://github.com/ZencashOfficial/repo/issues
The problem reported is not specific to the ZENCash Desktop GUI Wallet but concerns the entire APT repository. I am sure @cronicc will look into it...

**Comment by cronicc** [comment]
Resolved, see https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/73#issuecomment-368325988
