### ISSUE TITLE
Transfer times

### ISSUE THREAD

**Issue by Canefire** [ZencashOfficial/zencash-swing-wallet-ui#40]
I made a couple test transfers that went through quickly before starting to use the Wallet for mining. Yesterday at 2:50 PM (about 19 hours ago) my first mining transfer from ZenWallet to Cryptopia  has not registered as pending on CPIA yet, and shows as a NO on the wallet confirmation column. Is there some transmission time issue I should be aware of, or is this long a wait normal?

**Comment by Canefire** [comment]
Deposit showed up about 22 hours after transfer.

**Comment by vaklinov** [comment]
To make a sure a transaction will be confirmed by the ZEN network, you can increase the transaction fee to be larger than the default 0.0001. Once you send out a transaction you can also track its status on the ZEN block explorer https://explorer.zensystem.io/

**Comment by Canefire** [comment]
Ahh...thanks, adding something to the fee is a great idea. How do I know what block to search for on the block explorer though? All I have are the send and receive addresses.

**Comment by vaklinov** [comment]
You can search for block/transaction or address. Here is for instance the URL for an address:
https://explorer.zensystem.io/address/znkmhwKuEv4mWDBrWrV9dbAYQAYrL54QhQ7

**Comment by zenportodev** [comment]
Support case - no further information received.
