### ISSUE TITLE
Secret Phrase

### ISSUE THREAD

**Issue by hoyanf** [ZencashOfficial/zencash-swing-wallet-ui#41]
Where can I get the secret phrase from the wallet created ? private key ?

Thanks

**Comment by vaklinov** [comment]
The ZENCash Desktop GUI Wallet is technically a UI wrapper over the ZENCash command line tools. The ZEN private keys are stored in the wallet.dat file and it does not yet support encryption at file level. For that matter ZCash does not support encryption yet either... Using the wallet on a system infected with malware may result in wallet data/funds being stolen. Encryption will surely be supported in the future. There is currently no "secret phrase"...

One ZEN wallet that already supports encryption is Arizen:
https://github.com/ZencashOfficial/arizen

**Comment by Kimland** [comment]
I don't quite get the security of ZCash wallet.  If private keys are kept in the wallet,  what would keep the account private?   Does it mean anyone logging on the computer has access to the wallet?   Can it be installed on an electrum USB?

**Comment by vaklinov** [comment]
The private keys are inside the `wallet.dat`. However they are only as private as your PC is secure! If anyone else gains access to your PC, this privacy may be compromised! The `wallet.dat` file does not yet support encryption at file level.
