### ISSUE TITLE
Can I restore an old eleos backup in swing?

### ISSUE THREAD

**Issue by VicAgbasi** [ZencashOfficial/zencash-swing-wallet-ui#42]
Is it possbile to restore an old eleos backup in swing?

**Comment by vaklinov** [comment]
If the Eleos wallet backup is in the form of a `wallet.dat` file, it can be moved from Eleos to the ZENCash Desktop GUI Wallet - yes. The file `wallet.dat` may only be moved/replaced when the wallet/zend are **not** running.

**Comment by VicAgbasi** [comment]
Thanks a lot man. I will try that out!...
  
  
  

  
  

  
  
>

**Comment by zenportodev** [comment]
Support case - no further information received.
