### ISSUE TITLE
code 1 error

### ISSUE THREAD

**Issue by rokazulu** [ZencashOfficial/zencash-swing-wallet-ui#43]
I'm getting this error when I startup the wallet.

I attempt to fix it by going in the terminal and typing zend -reindex
but that isn't a recognized command.

**Comment by vaklinov** [comment]
As written in the ZENCash Desktop GUI Wallet troubleshooting guide:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md
On Windows you first have to locate zend.exe. It is in the /app sub-directory of the wallet installation. The console/cmd needs to have as current directory the /app sub-directory of the wallet installation for the command `zend -reindex` to work.

**Comment by rokazulu** [comment]
Alright, I did the command correctly now and I still seem to be getting the same error.

**Comment by vaklinov** [comment]
If you attach logs/screenshots of the error, maybe I could help you ...

**Comment by tbonesjones** [comment]
Hello.  I have been having the same error when starting up my wallet.  I have located the zend.exe app but when I try to run I get "zend.exe has stopped working"  A problem caused the program to stop working correctly.  Any idea how to correct that?  Thank you

**Comment by vaklinov** [comment]
If you start it via command line as `zend -reindex` and zend still crashes (zend.exe has stopped working). maybe you have some irreparable blockchain corruption... One thing you could try is to backup the existing wallet and blockchain, and start synchronization from 0 again (make sure you preserve your `wallet.dat`).

**Comment by tbonesjones** [comment]
Ok I have backed up wallet.dat.  Do I delete the rest of zen files and redownload the wallet start synchronization again? @vaklinov

**Comment by rokazulu** [comment]
[ZENCashGUIWallet_2017_12_debug.log](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/files/1536720/ZENCashGUIWallet_2017_12_debug.log)

**Comment by rokazulu** [comment]
![untitled](https://user-images.githubusercontent.com/7477191/33683283-fa567e14-da8f-11e7-9ca3-187238e59793.jpg)

**Comment by vaklinov** [comment]
@tbonesjones You may start fresh with a new/clean directory `%APPDATA%/Zen`. It is better not to delete the old directory but rename and keep it (just in case). Make sure you put your `wallet.dat` into the new `%APPDATA%/Zen` before you start the GUI wallet.

@rokazulu Are you sure the command `zend -reindex` was successfully executed and started zend? I think maybe it did not... If `zend -reindex` was successfully executed we need to see what error may exist in `%APPDATA%/Zen/debug.log`

**Comment by tbonesjones** [comment]
Ok so how do I restart the synch? @vaklinov

**Comment by vaklinov** [comment]
@tbonesjones More detailed procedure:
1. Rename existing %APPDATA%/Zen to %APPDATA%/Zen_old

**Comment by vaklinov** [comment]
@tbonesjones More detailed procedure:
1. Make sure GUI wallet and zend are stopped
2. Rename existing `%APPDATA%/Zen` to `%APPDATA%/Zen_old`
3. Create new empty `%APPDATA%/Zen`
4. Copy `wallet.dat` from `%APPDATA%/Zen_old` to `%APPDATA%/Zen`
5. Start the GUI wallet to begin synchronization...

The above may need be done only if you have some irreparable blockchain corruption.

**Comment by vaklinov** [comment]
@adriane93 Reindexing normally takes a few hours only. While it is very unusual for it to last 2 days+, if possible it is better to leave it to finish. If it does not finish, you may have to start it over again when you need to use the wallet.

To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

**Comment by nygellyndley** [comment]
@adriane93 i don't think the indexing ever stops, once it's complete it just sits there watching for new transactions.

I believe you can safely stop it once the block height has reached the current block height. http://explorer.zenmine.pro/insight/

It should certainly be there by now.

**Comment by Sodelll** [comment]
Hello!
I get the same problem with the wallet and i tried to do as you said but my zend.exe won't open. I mean it opens and then closes automatically right after i open it

**Comment by vaklinov** [comment]
@adriane93 Indeed when you reindex, zend will not atop automatically after reindexing. You need to eventually stop it by hand.

@Sodelll If zend does not start properly, you need to start zend from a command propmt (cmd) with a -reindex option. If you only click on it, it will not run as expected due to (probably) the broken blockchain you have. Here are some useful links on how to do it:
https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

**Comment by zenportodev** [comment]
Support case - no further information received.
