### ISSUE TITLE
ZENCASH WALLET (Fonts garbled)

### ISSUE THREAD

**Issue by JIMMY0512** [ZencashOfficial/zencash-swing-wallet-ui#44]
I am using 0.74.2 in windows 10 1511, (Traditional Chinese System)
ZENCASH WALLET TITLE FONTS WAS GARBLED, LIKE THE IMAGE. 

![20171205185713](https://user-images.githubusercontent.com/34270872/33603773-a96f0f76-d9ee-11e7-8f08-9ba32fb26cf1.jpg)

**Comment by vaklinov** [comment]
The two problematic labels are both characterized by an unusual font - Helvetica:
Font("Helvetica", Font.BOLD | Font.ITALIC, 28)
Is the Helvetica font available on the Windows system?

**Comment by JIMMY0512** [comment]
Yes, I have installed 2 fonts already, the font still garbled.

**Comment by zenportodev** [comment]
@JIMMY0512 The newest wallet version has changed the way it displays fonts (of the problematic labels). If you try it, could you possibly attach a screen-shot of what it looks like on a Chinese system...

**Comment by St3x** [comment]
Does this still happen with the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases) ?
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
