### ISSUE TITLE
Unable to locate package zen

### ISSUE THREAD

**Issue by firsttubr** [ZencashOfficial/zencash-swing-wallet-ui#45]
When I run the install I get the following errors:
W: Failed to fetch https://zencashofficial.github.io/repo/dists/rosa/main/binary-amd64/Packages  HttpError404

W: Failed to fetch https://zencashofficial.github.io/repo/dists/rosa/main/binary-i386/Packages  HttpError404

E: Unable to locate package zen
E: Unable to locate package zencash-desktop-gui-wallet

trying to install on linux mint,

thanks

**Comment by vaklinov** [comment]
This may be a bug but it is a problem of the APT repository (not of the GUI wallet). Please report the problem in the repository project: https://github.com/ZencashOfficial/repo/issues

I am sure @cronicc will look into it.

**Comment by cronicc** [comment]
Resolved, see https://github.com/ZencashOfficial/zencash-swing-wallet-ui/issues/73#issuecomment-368325988
