### ISSUE TITLE
Update to v2.0.10-1 binaries

### ISSUE THREAD

**Issue by 2ge** [ZencashOfficial/zencash-swing-wallet-ui#46]
there is new binaries out https://github.com/ZencashOfficial/zen/releases which fixing couple of bugs. Do you plan to update Wallet, or write article how to update it by replacing binaries ? Thanks

**Comment by vaklinov** [comment]
Yes, I am planning to make new wallet releases in the next 1 month that will include the new binaries. It ought to be possible (for someone who cannot wait) to just take zend.exe and zen-cli.exe from the new released ZEN binaries and replace them in the older wallet releases. However I have not tested this yet and it may not work 100%. I intend to test soon...

**Comment by zenportodev** [comment]
Solved - long ago.
