### ISSUE TITLE
Transaction from Bittrex ZEN wallet to swing wallet states invalid

### ISSUE THREAD

**Issue by TeeVee17** [ZencashOfficial/zencash-swing-wallet-ui#47]
My ZenCash Wallet is fully synchronized so I sent a small amount of ZEN cash from my bittrex wallet to my address set up on the the zencash wallet but Bittrex marks the transaction as invalid after a few minutes. it shows the txID is null but that is the only information on the failure so I can't figure out what the issue is. I tried to transfer .25 ZEN so was wondering if there is a min size or if another issue is lurking?

Also is there a way to clear out addresses as I added too many and it is confusing. There is not way to determine if its private or transparent account address either.

**Comment by vaklinov** [comment]
There are several issues here:
1. Outgoing transactions from Bittrex do not work (in your case). To check if the transaction is actually on the blockchain use the ZEN explorer: https://explorer.zensystem.io/
2. Deleting addresses from the wallet is not possible (as of now - not supported)
3. The T addresses in the wallet can be distinguished from the Z addresses: Z addresses are longer and start with zc...

**Comment by zenportodev** [comment]
Support case - no further information received.
