### ISSUE TITLE
Zencash Wallet Version 0.74.7 Sending Incorrect Amounts

### ISSUE THREAD

**Issue by obagam** [ZencashOfficial/zencash-swing-wallet-ui#49]
Using on Mac OS Sierra 10.12.6. When I execute a transfer the amount is correct. When it reaches the blockchain it's an incorrect  amount to a completely different address listed in my wallet not the wallet that was intended.

**Comment by vaklinov** [comment]
If you send ZEN from a T address its original balance is spent entirely in 3 parts:
1. The original amount sent to the intended destination
2. The transaction fee to the miners
3, The remaining balance is sent to another T address in the same wallet. This is a feature that comes from Bitcoin (the ZEN code-base). This point sometimes confuses users...

Could you please point to your transaction on the blockchain and specify: how much ZEN you intended to send and to which address and what part of the transfer was wrong. You could try this with a small amount just for the exercise...

Example transaction:
https://explorer.zensystem.io/tx/1283c4698e54dcb8f32928857c5ff51e850a9f5efa099d46ba36bdfc1505aede
here "some" user znbKhxbbJnFar1GaxTiAZjtTv7EX4yM4Dgu had 11.10163 zen. He sent 10 ZEN to address znarmmN6KNBxUMPVVG8kw7CTZJN2J5pU9gR and the remaining balance 1.10163 zen was automatically sent to another address in his wallet: znbKhxbbJnFar1GaxTiAZjtTv7EX4yM4Dgu ...

**Comment by zenportodev** [comment]
Support case - no further information received.
