### ISSUE TITLE
Market cap

### ISSUE THREAD

**Issue by Djannose** [ZencashOfficial/zencash-swing-wallet-ui#52]
Add real time market cap to wallet

**Comment by vaklinov** [comment]
Accepted as an enhancement.

**Comment by St3x** [comment]
The latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases) shows the ZEN capitalization.
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
