### ISSUE TITLE
join split error in swing newest version

### ISSUE THREAD

**Issue by phobos777** [ZencashOfficial/zencash-swing-wallet-ui#54]
![image](https://user-images.githubusercontent.com/15862598/34393268-3f9be5d2-eb1f-11e7-8e7f-b7f28ecc6386.png)

When transfering out of a ZN private address.  i get this error.  any tips?  TIA!

**Comment by vaklinov** [comment]
This error is reported by the ZEN core software. Please check the log file `%LOCALAPPDATA%/ZENCashSwingWalletUI/ZENCashGUIWallet_xxxx_xx_debug.log` to see the exact form of the command being executed via `zen-cli.exe`. If the source address has enough balance and yet this error is still reported, this problem needs to be reported to ZEN core developers here: https://github.com/ZencashOfficial/zen/issues

**Comment by phobos777** [comment]
Here is the log results:   you can see the errors.   if this looks correct to you.  i'll report to Core Devs:  :)

[Thread-21912] [Fri Dec 29 06:50:00 EST 2017] [INFO] Operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status is [{"id":"opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a","status":"executing","creation_time":1514548073,"method":"z_sendmany","params":{"fromaddress":"zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq","amounts":[{"address":"zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw","amount":2.50}],"minconf":1,"fee":0.0001}}]. 
[Thread-21912] [Fri Dec 29 06:50:00 EST 2017] [INFO] Checking for operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status done in 9300ms. 
[Thread-95] [Fri Dec 29 06:50:00 EST 2017] [INFO] Gathering of dashboard daemon status data done in 51996ms. 
[Thread-21912] [Fri Dec 29 06:50:02 EST 2017] [INFO] Operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status is [{"id":"opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a","status":"executing","creation_time":1514548073,"method":"z_sendmany","params":{"fromaddress":"zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq","amounts":[{"address":"zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw","amount":2.50}],"minconf":1,"fee":0.0001}}]. 
[Thread-21912] [Fri Dec 29 06:50:02 EST 2017] [INFO] Checking for operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status done in 216ms. 
[Thread-21912] [Fri Dec 29 06:50:05 EST 2017] [INFO] Operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status is [{"id":"opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a","status":"failed","creation_time":1514548073,"error":{"code":-26,"message":"18: bad-txns-joinsplit-requirements-not-met"},"method":"z_sendmany","params":{"fromaddress":"zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq","amounts":[{"address":"zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw","amount":2.50}],"minconf":1,"fee":0.0001}}]. 
[Thread-21912] [Fri Dec 29 06:50:05 EST 2017] [INFO] Checking for operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status done in 286ms. 
[AWT-EventQueue-0] [Fri Dec 29 06:50:05 EST 2017] [INFO] Operation opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a status is [{"id":"opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a","status":"failed","creation_time":1514548073,"error":{"code":-26,"message":"18: bad-txns-joinsplit-requirements-not-met"},"method":"z_sendmany","params":{"fromaddress":"zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq","amounts":[{"address":"zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw","amount":2.50}],"minconf":1,"fee":0.0001}}]. 
[Thread-21912] [Fri Dec 29 06:50:07 EST 2017] [INFO] Ending data gathering thread Thread-21912 ... 
[Thread-96] [Fri Dec 29 06:50:09 EST 2017] [INFO] Gathering of dashboard wallet balance data done in 763ms.

**Comment by phobos777** [comment]
3-4 transactions (and errors above)  tried different addresses.

**Comment by vaklinov** [comment]
@phobos777 Indeed the send operation details:
```
{"id":"opid-8cce37bf-6b54-4c2f-bdfb-b9154fd1ce6a",
"status":"failed",
"creation_time":1514548073,
"error":{"code":-26,"message":"18: bad-txns-joinsplit-requirements-not-met"},
"method":"z_sendmany","params":{
"fromaddress":"zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq",
"amounts":[
{"address":"zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw","amount":2.50}],
"minconf":1,"fee":0.0001
}
}
```
seem to indicate this is a ZEN core issue. You are trying to send 2.5 ZEN from Z address:
`zcK9vH9Dbkw34trYq14xyrYQxEe4mVAyoB3esKN2UNdBNBEcNBCfX6pcUEWQbNUEbehrS23jJfysaC3U7EowSYECVG8L5uq` to T address `zna1xgvDAHNWNY72Mdj7Xi4zHYrqQUwnmAw`. This should be possible if the Z address has sufficient balance.

Please report it to the core devs ;-)

**Comment by PeaStew** [comment]
You will need to start zend with 'zend.exe --rescan'

**Comment by zenportodev** [comment]
Not a GUI problem per se...
