### ISSUE TITLE
cannot highlight / copy the total balance

### ISSUE THREAD

**Issue by FlorinAndrei** [ZencashOfficial/zencash-swing-wallet-ui#55]
I want to copy the total balance from the wallet app. I'm trying to highlight the value, then CTRL-C. But the app won't let me highlight it.

I'm running the app on Windows 10.

Please fix.

**Comment by vaklinov** [comment]
Accepted as an enhancement.

**Comment by St3x** [comment]
Still happens in 0.85.0.
Replacing the "label" with a "disabled input box" would allow the user to select and copy the balance.

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
