### ISSUE TITLE
Mac download failing Quickhash verification repeatedly

### ISSUE THREAD

**Issue by flemml** [ZencashOfficial/zencash-swing-wallet-ui#56]
Tried both 0.74.7 and 0.73.4 Swing wallets and the suggested Quickhash verification - neither passes repeated attempts

**Comment by vaklinov** [comment]
I have just tried to download again ZENCashWallet-0.74.7.dmg and the SHA256 checksum is as expected:
```
b7ff9e45909ec2fd17cb3629a5212b902e06f3f8a41a9f2ea427d2025356b82e  ZENCashWallet-0.74.7.dmg
```

**Comment by flemml** [comment]
Yes, just tried it again and again get same result.
<img width="1016" alt="screen shot 2018-01-01 at 1 20 14 pm" src="https://user-images.githubusercontent.com/34991589/34471173-a1164fd4-eef6-11e7-8504-1212dd1d8913.png">

**Comment by vaklinov** [comment]
You need to compute the hash of the downloaded file `ZENCashWallet-0.75.9.dmg` before any installation is made. It seems you are hashing the already installed wallet in /Applications/ZENCashWallet.app...

Please select the file `ZENCashWallet-0.75.9.dmg` for hashing. Another way to compute the hash on a Mac via command line only is:
```
shasum -a 256 ZENCashWallet-0.75.9.dmg
```

**Comment by zenportodev** [comment]
No further information received.
