### ISSUE TITLE
Selecting the blockchain storage directory

### ISSUE THREAD

**Issue by disasterovich** [ZencashOfficial/zencash-swing-wallet-ui#57]
Hi

I would like to be able to change the blockchain directory. Perhaps through some parameter in zen.conf or by selecting a directory during the installation process.

![screenshot_2](https://user-images.githubusercontent.com/391202/34467486-96d28c32-ef04-11e7-8c5b-42742eb932a0.png)

**Comment by vaklinov** [comment]
Accepted as an enhancement request.

**Comment by Sto1cNate** [comment]
@zennermac is this not already integrated through the datadir flag passed to zend?

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
