### ISSUE TITLE
Include txid info 

### ISSUE THREAD

**Issue by megaluck** [ZencashOfficial/zencash-swing-wallet-ui#6]
Include the txid field in the Transactions TAB,  Also on the pop-up that displays after making a Transaction, would be a good idea to include the txid there also.

**Comment by vaklinov** [comment]
Accepted as an enhancement - will be done.

**Comment by vaklinov** [comment]
This feature is now implemented: After sending ZEN successfully the user may copy the transaction ID to the clipboard or view the transaction on the blockchain explorer. 

![zen sent](https://user-images.githubusercontent.com/22178263/32983445-5ea05c9c-cc9d-11e7-9ca4-04481306f318.png)
