### ISSUE TITLE
no zend in /src

### ISSUE THREAD

**Issue by LeoLeeee** [ZencashOfficial/zencash-swing-wallet-ui#60]
As I followed the installation ,there is no zend or zen-cli in the /src package

**Comment by vaklinov** [comment]
I suppose you followed the ZEN core/node installation procedure:
https://github.com/ZencashOfficial/zen/blob/master/README.md
If it does not work for you as expected you need to report this issue on the project site of the ZEN  ZEN core/node:
https://github.com/ZencashOfficial/zen/issues

**Comment by zenportodev** [comment]
Not a GUI problem per se...
