### ISSUE TITLE
My ZenCash wallet says it is "not running" 

### ISSUE THREAD

**Issue by bethscapade** [ZencashOfficial/zencash-swing-wallet-ui#61]
My ZenCash wallet says it is "not running"  and I cannot find it listed on my programs for windows 10
In the bottom righthand corner of the wallet it says it is blockchain synchronized up until 
December 11, 2017. Do I need to download a new wallet?

**Comment by vaklinov** [comment]
So the GUI says that zend is NOT RUNNING. This is not expected but maybe zend has a problem and stops running. Some questions:
1. Did the wallet run successfully for some time (days/weeks) before you started getting the NOT RUNNING MESSAGE?
2. Are you able to make payments/create new addresses while the GUI says that zend is NOT RUNNING?
3. If you open the Windows task manager do you see zend running while GUI says that zend is NOT RUNNING?

Finally if the blockchain does not get synchronized after Dec 11th, you may have a broken blockchain. You may try reindexing as described in the troubleshooting guide: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

**Comment by zenportodev** [comment]
Support case - no further information received.
