### ISSUE TITLE
~/build-dir/zencash-swing-wallet-ui$ ant -buildfile  issue

### ISSUE THREAD

**Issue by HLC86** [ZencashOfficial/zencash-swing-wallet-ui#62]
user@ubuntu:~/build-dir/zencash-swing-wallet-ui$ ant -buildfile ./src/build/build.xml

result: error: package javax.xml.bind is not visible I am using a mac with java-9, google search shows that is due to java-9, any workaround here? i guess there must be some mac users who tried the same wallet setup. Thanks!

**Comment by vaklinov** [comment]
I can confirm that the build does not work out of the box with JDK9. JDK9 is modularized and some packages like javax.xml.bind need additional options to be made available/visible. Until this is fixed in the wallet build, please use JDK 8 to compile the wallet.

**Comment by zenportodev** [comment]
This is fixed in the latest Git/master branch.
