### ISSUE TITLE
Creating the Release page in Github for the Zencash Swing Wallet UI

### ISSUE THREAD

**Issue by kevintanhongann** [ZencashOfficial/zencash-swing-wallet-ui#63]
https://help.github.com/articles/creating-releases/

I think the visibility for the releases for the binary for the swing wallet is not that great in the sense that the general public will not be bothered to clone the repo and run the terminal commands.

If releases can be automated and binaries being published in the Releases section of this Github repo, then adoption of the desktop swing wallet can be better.

**Comment by vaklinov** [comment]
We have a section of binary releases:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases
The release process is not yet fully automated. There are plans to do this .. this year.

**Comment by St3x** [comment]
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
