### ISSUE TITLE
the "own identity" setting does not want to exit

### ISSUE THREAD

**Issue by aleqx** [ZencashOfficial/zencash-swing-wallet-ui#65]
0.75.8 on Windows. Going to settings "own identity" oepns a screen which does not want to close unless you fill in the fields. Obviously that's not mandatory given it works if you don't open the "own identity" setting in the first place.  Please allow closing it if empty.

**Comment by vaklinov** [comment]
There is indeed a problem in that the user is forced to enter a nickname (only nickname is mandatory) and click the button to continue. It is not possible to cancel the creation of a messaging identity altogether.

... to be fixed in the future..

**Comment by zennermac** [comment]
Now that we have Sphere By Horizen available with messaging built in, i anticipate that this will likely not be fixed.
