### ISSUE TITLE
Zencash transaction 0 confirmation 5 days ago

### ISSUE THREAD

**Issue by SongZhizhai** [ZencashOfficial/zencash-swing-wallet-ui#66]
https://explorer.zensystem.io/tx/bfbad1d6165e5acb74ab789ed8de23efb0e5ec274a6add2c5625f323c94bf72e
address：zniUsiA235ietm5ZJ2Kno2k42zJKm3G7Tzr

**Comment by vaklinov** [comment]
The transaction fee is 0. By default the ZENCash Desktop GUI Wallet has a fee of 0.0001 ZEN. I suppose the fee was manually set to 0...

The fact that a zero-fee transaction is not confirmed, is not a problem of the GUI Wallet but it is an issue for miners/core/node functionality. Unfortunately (as with Bitcoin) a zero fee transaction is not guaranteed to be confirmed...

**Comment by SongZhizhai** [comment]
@vaklinov 
I know.So,can I retract this transaction and submit again after I add a fee?

**Comment by vaklinov** [comment]
The transaction is now confirmed ;-)

**Comment by St3x** [comment]
This address has 0 ZEN now (https://explorer.zensystem.io/address/zniUsiA235ietm5ZJ2Kno2k42zJKm3G7Tzr).
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
