### ISSUE TITLE
Wallet crashes when opening "Error invoking Method"

### ISSUE THREAD

**Issue by humanhorn** [ZencashOfficial/zencash-swing-wallet-ui#7]
Wallet was working fine this morning. tried to open after rebooting PC and comes up with error "Error invoking method" and "failed to launch JVM"

**Comment by humanhorn** [comment]
Re-downloaded the wallet and seems to work fine now

**Comment by vaklinov** [comment]
In case of problems logs are written in `%LOCALAPPDATA%\ZENCashSwingWalletUI\` for diagnostics. It would help if you attach the log file `ZENCashGUIWallet_2017_09_debug.log`. If however the JVM does not start maybe this log does not record the crash at all. In which log file did you see the messages: ` "Error invoking method" and "failed to launch JVM`

Please also specify which wallet version you are running. I suppose 0.73.1 for Windows...

**Comment by vaklinov** [comment]
The problem reported did not become clear... no logs provided. Closing issue.
