### ISSUE TITLE
Linux Mint 17 Install

### ISSUE THREAD

**Issue by MHTheCount** [ZencashOfficial/zencash-swing-wallet-ui#74]
Thanks for all the good work Cronicc for adding the Linux Mint 17 distro. I loaded via Terminal and all appeared to go well until the last!!  See bellow: 

~ $ zen-fetch-params
zen-fetch-params: command not found

Any suggestions please? Thanks again

**Comment by vaklinov** [comment]
@MHTheCount Please check if after installing the Zen package you have on your system the following files:
```
-rwxr-xr-x root/root 119755072 2018-02-21 18:56 /usr/bin/zend
-rwxr-xr-x root/root   8734736 2018-02-21 18:56 /usr/bin/zen-cli
-rwxr-xr-x root/root      3374 2018-02-21 18:56 /usr/bin/zen-fetch-param
```

**Comment by vaklinov** [comment]
To find out if the files really exist, it is best to use a Linux terminal. Please type the command:
```
ls -lh /usr/bin/zen*
```
and we will see if it will list the files or not...

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one, no response from the OP in a year.
