### ISSUE TITLE
Swing wallet multiple issues at once! Help given

### ISSUE THREAD

**Issue by Gerbest** [ZencashOfficial/zencash-swing-wallet-ui#75]
Hey there!
I just went through multiple issues with my swing wallet, and I would like to share, so if it helps anyone, I'll be happy to know.

I had my Swing wallet installed for some time now, and it was receiving regular payments from my mining rig.
Wallet was constantly synced and I regularly got 8 connections validating.

**Error 1:**

Than I left the wallet without sync for 7 days and coincidently or not, I sent a manual payment to the wallet from my mobile (from Suprnova pool) to show a friend how it was done, with a small amount (the PC was turned off) and for the first time, I had an Orphaned block.

![orphaned](https://user-images.githubusercontent.com/32662088/36730340-d97ee990-1ba5-11e8-9df8-9d5eee42c5ce.JPG)

The transfers from the mining rig to the desktop wallet was being made to a T address. (This detail will be important for a later explanation.

Later, I tried to to access the swing wallet, and I started to get CODE -1 Error.
**Found the solution here:**
[https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/]
Left the computer reindex the ZEND file (it may take a day) and finally I could access the wallet.

![error code 1](https://user-images.githubusercontent.com/32662088/36730319-c6a112da-1ba5-11e8-968b-037ec2b044e7.JPG)

**Error 2:**
I tried to move my coins from my swing wallet to a mobile wallet. and I started getting Code 8 Error.

![error code 2](https://user-images.githubusercontent.com/32662088/36730354-e43cb362-1ba5-11e8-8651-623f2cf984eb.JPG)

**I found the solution somewhere, that before you try to move out from the swing wallet, you should first transfer from the T address to a Z Address. **

**Error 3:**
After moving the amount from the T address to the Z address, I tried to send once more,  and again I got an error that didn't accept any memo in that transfer.

**The solution was to just delete the memo and leave it blank, and finally I could make the transfer to the mobile wallet.**

Personal comments:

So, in resume, I believe there is a real big opportunity for improvements with respect to the basics for proper use from people that don't have to understand about this tech... Where they can just open the app, do their business and leave...

18 hours so solve all the issues above is waaaayy to much for common people adoption.

Please understand, I love the project, and before anyone thinks that I am just complaining, I just left above how a noob as I am can get away with it in just one post, because to solve all this, I had to navigate a while...
Plus, my natural language is Brasilian Portuguese, so I apologize for any grammatical mistake.

**Comment by vaklinov** [comment]
Thank you for the detailed report. I understand there are usability improvements that can be made here. Some comments on the specific issues:

Error 1: To make sure it does not happen again, you need to use the latest version of the wallet (for Windows - 0.75.8a). The underlying technical cause is not in the GUI itself but in the ZEN core/node. 

Error 2: This problem is exclusive to miners but there is not much the GUI can do. If you read the fine print on the "Send Cash" UI panel, you will see a warning about this.

Error 3: Indeed, usability will be improved here.

**Comment by St3x** [comment]
Is this still relevant ?
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
