### ISSUE TITLE
Couldn't connect to server

### ISSUE THREAD

**Issue by sidpun10** [ZencashOfficial/zencash-swing-wallet-ui#76]
I'm facing this attached issue while trying to open my wallet. Any insights?
![image](https://user-images.githubusercontent.com/37024195/36937467-368e8268-1ed9-11e8-8372-c573c5df5127.png)

**Comment by sidpun10** [comment]
This is what shows up in error log.

[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Starting ZENCash Swing Wallet ... 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] OS: Windows 10 = WINDOWS 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Current directory: C:\Users\Sid\Downloads\ZENCashDesktopGUIWallet_0.74.2\app 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Class path: C:\Users\Sid\Downloads\ZENCashDesktopGUIWallet_0.74.2\app\ZENCashSwingWalletUI.jar;bitcoinj-core-0.14.5.jar 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Environment PATH: C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\PuTTY\;C:\Users\Sid\AppData\Local\Microsoft\WindowsApps 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Using ZENCash utilities: zend: C:\Users\Sid\Downloads\ZENCashDesktopGUIWallet_0.74.2\app\zend.exe, zen-cli: C:\Users\Sid\Downloads\ZENCashDesktopGUIWallet_0.74.2\app\zen-cli.exe 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] zend is not runing at the moment or has not started/synchronized 100% - showing splash... 
[main] [Sat Mar 03 11:46:41 CST 2018] [INFO] Splash: checking if zend is already running... 
[main] [Sat Mar 03 11:46:44 CST 2018] [INFO] Splash: zend will be started... 
[main] [Sat Mar 03 11:47:00 CST 2018] [ERROR] Unexpected error:  
java.io.IOException: error: couldn't connect to server: EOF reached (code 1)
(make sure server is running and you are connecting to the correct RPC port)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:172)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:564)

**Comment by vaklinov** [comment]
You are experiencing the known problem of a broken local block-chain. As a start you need to download and instal the latest GUI wallet:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases/tag/0.75.8
Then you need to reindex the blockchain.

The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/

To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

Once you make sure you have a wallet backup in a safe place, the broken-blockchain problem is most commonly solved by re-indexing the block-chain. For details of how to reindex, see the troubleshooting guide: https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md

The following step-by-step guide for Windows users (created by a third party) is also handy: https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/ to help with reindexing in case of encountering the common block-chain problem.

**Comment by sidpun10** [comment]
Thanks you so much for the prompt reply. I really appreciate.
