### ISSUE TITLE
Zen Swing Wallet uses only 1 CPU core

### ISSUE THREAD

**Issue by lmannyr** [ZencashOfficial/zencash-swing-wallet-ui#77]
I noticed that when updating the blockchain, swing wallet is only using one core.  Anyway to allow it to use multiple cores for faster blockchain updates?

**Comment by vaklinov** [comment]
The actual process of on-disk block-chain synchronization is not done by the GUI but by the ZEN core/node. The right place to report this issue is: https://github.com/ZencashOfficial/zen/issues

**Comment by St3x** [comment]
Can this issue be closed as it's not a Swing Wallet one ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
