### ISSUE TITLE
File won't unzip

### ISSUE THREAD

**Issue by fakeleadman** [ZencashOfficial/zencash-swing-wallet-ui#79]
I am at a loss. I have downloaded both Windows versions, (8 and 8a) and neither of them will unzip completely. Using two different zipping software, I get the same effective result. In Opener Pro, it says "Archive corrupted" and using WinZip, it says the files, starting with several .dll files and the all important GUI.exe file, could not be created. The zip file is in my downloads folder and I am using the primary (and only) login on my personal computer, so administrative privileges should not be an issue. Please help!

**Comment by vaklinov** [comment]
I would suspect some download problem in this case. The Windows ZIPs are created with 7-Zip andso far no such problems have been reported - especially the older version 0.75.8 (made in Dec 2017) has bene used many time.

Could you please verify the checksum of the download e.g.:
1. Download the Wallet ZIP file ZENCashDesktopGUIWallet_0.75.8a.zip:
https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases/download/0.75.8/ZENCashDesktopGUIWallet_0.75.8a.zip
2. Using a tool such as http://quickhash-gui.org/ you may calculate the its SHA256 checksum. The result should be:
```
2f8eee60181aed5475b1c82051c7b8abae31cd418384eceb866ef09389b8e3ad  ZENCashDesktopGUIWallet_0.75.8a.zip
```

**Comment by fakeleadman** [comment]
I just downloaded the newest one, 0.80.5, ran the Quickhash, the sha256
checksum is correct, and it still would not open using Opener Pro. I then
downloaded 7-Zip and using that, it extracted fine. Apparently other
zipping programs are incompatible.

**Comment by St3x** [comment]
Can this resolved issue be closed ?
Don't forget to upgrade to the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases).

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
