### ISSUE TITLE
Wallet backing up in incorrect location

### ISSUE THREAD

**Issue by humanhorn** [ZencashOfficial/zencash-swing-wallet-ui#8]
When backing up wallet and specifying a location to save, it saves in the default directory C:\Users\home. Also there is no file extension on the backup file, i assume it should have a .dat extension?

**Comment by vaklinov** [comment]
Please pay attention to the one time message the wallet shows when you choose to backup your `wallet.dat` file for the first time. The restriction on having one location dir for backup and on the wallet file not having a `.dat` suffix comes from `zend`. Full message to users (shows once only) is:

![backup_info](https://user-images.githubusercontent.com/22178263/30004884-79f17e94-90df-11e7-9a8b-5d96b95efcb8.png)

**Comment by vaklinov** [comment]
The originally reported problem is currently a "feature".
