### ISSUE TITLE
Can't recover wallet.dat

### ISSUE THREAD

**Issue by CMcCullough41** [ZencashOfficial/zencash-swing-wallet-ui#80]
I regularly back up my computer, in case it ever crashes.

It crashed on me last night, and I went to restart the Zen Swing wallet after importing my old wallet.dat file (it's all I have, I never saved the private keys elsewhere, stupid me!) and I'm getting the couldn't connect to server: EOF reached (code 1) error. When I start zend directly, it instantly closes. I'm getting a Failed to rename wallet.dat to wallet.1521139373.bak error when I try that. 

My old wallet.dat is large... about 2.3 MB. I'm not sure what to do at this point... and I'm worried that my wallet.dat file is corrupted. Is there any hope for recovery?

Thanks in advance for any help... kinda at my wits end on this.

**Comment by vaklinov** [comment]
After your PC crashed there seem to be two problems: zend not starting and the wallet.dat not being loaded (worse). As a start to get zend running you may try to start it with the reindex option:

https://github.com/ZencashOfficial/zencash-swing-wallet-ui/blob/master/docs/TroubleshootingGuide.md
The following step-by-step guide for Windows users (created by a third party) is also handy: https://miningwithnvidia.com/2018/02/09/zencash-wallet-eof-reached-code-1/ to help with reindexing in case of encountering the common block-chain problem.

Then once zend starts successfully the wallet.dat issue is more critical: It is a good idea never to delete a  wallet.dat file but just rename it and back it up in case it is needed. So if your current wallet.dat cannot be loaded there is indeed a chance it is corrupted. In that case it may be good try try loading a backup wallet.dat ... Regarding recovering a corrupted wallet.dat: I have no experience here, maybe ZEN core devs can help :-(

Regarding wallet.dat backups: It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every 30-40 outgoing transactions) and it MUST also be backed up after creating a new Z address.

**Comment by siphon11** [comment]
Not sure that's the right place but need advice.
My computer crashed. All I have saved is my private key.
I downloaded ZENCashDesktopGUIWallet_0.80.5 but don't know how to recover my wallet / where to insert my private key in order to access my ZenCash.
Thanks for your help.

**Comment by zenportodev** [comment]
@siphon11 If you have your private key as text (not a file with private keys) you may use the option:
Wallet >> Import one private key

**Comment by St3x** [comment]
Can this resolved issue be closed ?

Don't forget to upgrade to the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases).

**Comment by siphon11** [comment]
Yes thanks.
 
-----Original Message-----

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
