### ISSUE TITLE
feature request - better coin control and transaction visibility

### ISSUE THREAD

**Issue by nikmit** [ZencashOfficial/zencash-swing-wallet-ui#81]
@cryptolawjunkie on telegram suggested that having better visibility of the available transactions within an address would be really good. Particularly when making payments from a wallet which contains stake addresses - would be nice to know in advance which transactions will be used and what will remain in the source address afterwards. Seems like a very good idea.

**Comment by vaklinov** [comment]
Accepted as an enhancement.

**Comment by zennermac** [comment]
Hey @nikmit 
This likely won't be implemented any time soon in this wallet.
Any questions like this should be directed to the Sphere Bt Horizen repo now
https://github.com/ZencashOfficial/Sphere_by_Horizen
