### ISSUE TITLE
Wallet stuck in "Activating Best Chain"

### ISSUE THREAD

**Issue by alejojb** [ZencashOfficial/zencash-swing-wallet-ui#83]
Hi I would like to know why when I start the wallet, it get stuck on "Activating Best Chain"
Already updated Java, restart the PC but still no good.

**Comment by St3x** [comment]
Is it still the case with the latest [release](https://github.com/ZencashOfficial/zencash-swing-wallet-ui/releases) ?
Can this issue be closed ?

**Comment by zennermac** [comment]
This is definitely not an issue in the latest release.
I'm going to close this out now.
