### ISSUE TITLE
Arch Linux instruction

### ISSUE THREAD

**Issue by Jzarecta** [ZencashOfficial/zencash-swing-wallet-ui#84]
Can someone add Arch Linux installation instructions?

**Comment by vaklinov** [comment]
Indeed this is a good idea (Arch Linux installation instructions). They need to be created by someone using Arch Linux ... so volunteers are welcome for this ;-)

**Comment by Jzarecta** [comment]
you can run an arch vm using vagrant, but the main issue is the sometimes issue with java, I tried to compile from source and got a lot of garbage named files. I could maybe make a pre-compiled vagrant image and you can get into your system and test over that environment.

**Comment by asbachb** [comment]
If someone is interested he can adopt the aur: https://aur.archlinux.org/packages/zencash-swing-wallet-ui-bin/

**Comment by cronicc** [comment]
Swing is in pure maintenance mode, no new features will be implemented anymore. Only critical bug fixes and compatibility releases for zend deprecations are being done.
