### ISSUE TITLE
How to recover my wallet

### ISSUE THREAD

**Issue by siphon11** [ZencashOfficial/zencash-swing-wallet-ui#88]
Hello,
My computer crashed. All I have saved is my private key.
I downloaded ZENCashDesktopGUIWallet_0.80.5 but don't know how to recover my wallet / where to insert my private key in order to access my ZenCash.
Thanks for your help.

**Comment by LordMajestros** [comment]
Open the app, go to wallet in the menu, select import one private key. Paste/type your private key and click import. Let it rescan the blockchain and you should see your zencash balance when it is done

**Comment by LordMajestros** [comment]
You may also have to let it redownload the blockchain depending on if that was lost in the crash too

**Comment by siphon11** [comment]
Thanks a lot. I was confused by the "import Private Key" menu that I tried without success.
Now, with your help, wallet is back, and the re-download of the blockchain is still on ....
Thank you again. I really appreciate your prompt response.
 
 
-----Original Message-----

**Comment by LordMajestros** [comment]
You're welcome 😀

**Comment by St3x** [comment]
Can this resolved issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
