### ISSUE TITLE
Warning message typo

### ISSUE THREAD

**Issue by pssm** [ZencashOfficial/zencash-swing-wallet-ui#89]
Typo in out-of-sync warning message:

<img width="494" alt="screen shot 2018-04-23 at 10 12 29" src="https://user-images.githubusercontent.com/125891/39117584-35b66ea4-46df-11e8-80aa-98e8463f0ea6.png">

Version 0.81.0

**Comment by zenportodev** [comment]
Bug is already fixed in the Git master branch.

**Comment by St3x** [comment]
Can this resolved issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
