### ISSUE TITLE
Allow sending a messaging identity to a Z address

### ISSUE THREAD

**Issue by vaklinov** [ZencashOfficial/zencash-swing-wallet-ui#9]
As noted by @blockops1 if two users use messaging, one efficient way to establish contact is for one to report his Z address for sending and receiving messages. The other user will then send his identity as a special message to this Z address. The first user may then do likewise...

This is more efficient than the current mechanism of sharing JSOn files.

**Comment by Sto1cNate** [comment]
@zennermac This should be able to be closed as the messaging system (ZenChat) implemented within Sphere requires only a key exchange, no passing of json files.

**Comment by zennermac** [comment]
Yes I am closing this out now as Sphere By Horizen is available.
I would recommend any suggested updates to messaging be added to the Sphere By Horizen repo.
https://github.com/ZencashOfficial/Sphere_by_Horizen
