### ISSUE TITLE
Recovering wallet

### ISSUE THREAD

**Issue by raythebull** [ZencashOfficial/zencash-swing-wallet-ui#94]
Hello, 
i am a bit desperate and need some help. I would like to access to my ZEN. I have only the text file. 
What should i do? I tried on myzenwallet.io to load it as a wallet.dat file but nothing happen, i tried to set up Arizen but could not retrieve my ZEN (Arizen crashes when i load the file).
Any other solutions? I spent hours on this...
I am really not a tech guy, sorry.
Thanks a lot for any help.
Ray

**Comment by PeaStew** [comment]
Hi Ray,

Could you please raise a ticket at https://support.zencash.com so we can deal with this problem for you?

Thanks!

**Comment by St3x** [comment]
Can this issue be closed now ?

**Comment by PeaStew** [comment]
Yes it can.

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
