### ISSUE TITLE
ERROR: 18: bad-txns-joinsplit-requirements-not-met

### ISSUE THREAD

**Issue by pmoses987** [ZencashOfficial/zencash-swing-wallet-ui#97]
Hello,

I have quite a bit of ZEN (at least for me) that is currently locked up in my Swing Wallet.  When I try to transfer cash, I get "ERROR: 18: bad-txns-joinsplit-requirements-not-met".

I've been able to access some of my cash by installing the Arizen wallet, but the majority of my holdings are in the private (z-address) wallet, and I can't import those into Arizen - or move them.

Any ideas on how to fix this error?  Or at least access my coins?

**Comment by LordMajestros** [comment]
Save your zaddress private key.
Rename your wallet.dat to old-wallet.dat and back it up too.
Start your swing wallet again, it should create a new wallet.dat
Import your z-address private key and try sending your coins to a t-address.

**Comment by LordMajestros** [comment]
If that does not work
You need to run open a command line window and type zencashd -rescan
So basically you need to run the Zencash daemon with the -rescan argument.

**Comment by zenportodev** [comment]
Indeed the problem of error message:
```
ERROR: 18: bad-txns-joinsplit-requirements-not-met
```
is not a GUI problem but comes from the ZEN core/node. Actually it also exists for other Z-currencies too. Rescanning the blockchain (run the Zencash daemon with the -rescan argument) usually solves it...

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
