### ISSUE TITLE
wallet  Address value error

### ISSUE THREAD

**Issue by juanchi0702** [ZencashOfficial/zencash-swing-wallet-ui#99]
I downloaded zencash-swing-wallet and executed it
Then get a own address
I execute a mining program and get the currency
But I found that my wallet didn’t have money
After the query found Address value error

What's wrong with my wallet?

**Comment by juanchi0702** [comment]
https://zen.miningspeed.com/workers/znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS

my wallet "own address" is znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS

but in https://explorer.zensystem.io/address/znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS

address is error?

**Comment by zenportodev** [comment]
As the block explorer shows:
https://explorer.zensystem.io/address/znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS
address znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS has received 0.09334263 zen (presumably from mining). 

The ZEN balance will be shown in the  ZENCash Desktop GUI Wallet only after the block-chain is fully synchronized (100%).

BTW: If you are not an experienced user, this wallet is probably not the most suitable one to use.

The ZEN private keys are located in the wallet.dat file in directory:
Windows: %APPDATA%/Zen/
Mac OS: ~/Library/Application Support/Zen/

To make sure your ZEN is not lost, the most important thing is to keep a backup copy of your wallet.dat file - it must never be lost! It may be copied manually when the GUI wallet/zend are not running. The wallet.dat needs to be backed up regularly (not just once - say after every few outgoing transactions) and it MUST also be backed up after creating a new Z address.

**Comment by St3x** [comment]
This address has actually 0.03086157 ZEN (https://explorer.zensystem.io/address/znSRBMs3GeqPYU7ya4tF8hjFhcAUHXLUTmS).
Can this issue be closed ?

**Comment by Sto1cNate** [comment]
@zennermac should be able to close this one.
